
services:
  backend:
    build: ./backend/investment-deal-room-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=${COSMOS_DB_CONNECTION_STRING}
      - SPRING_PROFILES_ACTIVE=prod
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}

  frontend:
    build: ./frontend/investment-deal-room-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
