apiVersion: v1
kind: Secret
metadata:
  name: dealroom-secrets
  namespace: dealroom
type: Opaque
stringData:
  COSMOS_DB_CONNECTION_STRING: "mongodb://investment-deal-room-db:XDlpasktGF6FJVP9SxNVmMguKxQ3HjeN0nnuC4o7KAQ9xDPA7DwvxYza8Wzw9PrBEpAZgsdLd4pAACDb47q2JA==@investment-deal-room-db.mongo.cosmos.azure.com:10255/investment-deal-room-db?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@investment-deal-room-db@"