# application-prod.yml
spring:
  data:
    mongodb:
      uri: ${COSMOS_DB_CONNECTION_STRING}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/f947665a-e85c-43ab-8198-2b8c8cbeb643/v2.0

app:
  cors:
    allowed-origin: https://dealroom-app.eastus.cloudapp.azure.com

management:
  endpoints:
    web:
      exposure:
        include: health