export enum PipelineStage {
    PROSPECTING = 'PROSPECTING',
    DUE_DILIGENCE = 'DUE_DILIGENCE',
    NEGOTIATION = 'NEGOTIATION',
    CLOSING = 'CLOSING',
    CLOSED_WON = 'CLOSED_WON',
    CLOSED_LOST = 'CLOSED_LOST'
}